config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/about'
  get 'pages/course'
  get 'pages/otzuv'
  get 'signup', to: 'users#new'
  resources :microposts,          only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true

  validates :content, presence: true, length: { maximum: 140 }
 
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
    validates :follower_id, presence: true
    validates :followed_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord

    has_many :microposts, dependent: :destroy
    has_many :active_relationships, class_name:  "Relationship",
    foreign_key: "follower_id",
    dependent:   :destroy
    has_many :passive_relationships, class_name:  "Relationship",
    foreign_key: "followed_id",
    dependent:   :destroy

    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower

    before_save { self.email = email.downcase }

    validates :username, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { minimum: 3, maximum: 25 }
        VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { maximum: 105 },
    format: { with: VALID_EMAIL_REGEX }

    has_secure_password


    def feed
        following_ids = "SELECT followed_id FROM relationships
        WHERE  follower_id = :user_id"
Micropost.where("user_id IN (#{following_ids})
        OR user_id = :user_id", user_id: id)
      end
       # Начать читать сообщения пользователя.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Перестать читать сообщения пользователя.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Возвращает true, если текущий пользователь читает сообщения другого пользователя.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :log
    before_action :logged_in?, only: [:create, :destroy]
    before_action :correct_user,   only: :destroy
    
    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
          flash[:primary] = "Micropost created!"
          redirect_to request.referrer
        else
            @feed_items = []
          render 'static_pages/home'
        end
      end
    
      def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
      end
    
      private
    
      def log
        @user = current_user
      end
        def micropost_params
          params.require(:micropost).permit(:content, :picture)
        end

        def correct_user
            @micropost = current_user.microposts.find_by(id: params[:id])
            redirect_to root_url if @micropost.nil?
          end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about
  end

  def otzuv 
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    before_action :logged_in?

    def create
        user = User.find(params[:followed_id])
        current_user.follow(user)
        redirect_to user
      
      end
    
      def destroy
        user = Relationship.find(params[:id]).followed
        current_user.unfollow(user)
        redirect_to user
      
      end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "Вы успешно вошли в свой профиль!"
        redirect_to user
      else
        flash.now[:alert] = "Вы где то допустили ошибку!"
        render 'new'
      end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:danger] = "Вы вышли из своего профиля!"
      redirect_to root_path
    end
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in?, only: [:following, :followers]

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
    
def new
    @user = User.new
end

def show 
  @microposts = @user.microposts.paginate(page: params[:page])
end

def otzuv 
  @user = User.find(session[:user_id])
  @microposts = @user.microposts.paginate(page: params[:page])
end

def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

def edit
    
end

def update
  if @user.update(user_params)
    flash[:notice] = "Ваш профиль был успешно обновлён!"
    redirect_to @user
  else
    render 'edit'
  end
end


def create
    usercode = params[:user][:code].downcase
    
    if usercode == "motobro24" 
      @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Добро пожаловать в наше сообщество #{@user.username}!"
      redirect_to user_path(current_user)
    else
      render 'new'
    end
    else
      flash[:danger] = "Неправильный код! Не знаешь? Тогда пиши в инстаграмм!"
      redirect_to signup_path
    end
  end
  
  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Ваш аккаунт успешно удалён!"
    redirect_to root_path
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "Вы можете обновить и удалить только свой аккаунт!"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  
  end



  end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small> &copy; <%= link_to "TikTok", "https://vm.tiktok.com/ZMJo1Gsh7/", class: "text-white" %></small></br>
    <small> &copy; <%= link_to "Instagram", "https://instagram.com/_ok_nel_set_?igshid=1hpw8a1ojq0sv", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "MotoBro", root_path, class: "navbar-brand", id: "logo" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Братья", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "О нас", pages_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Курс", pages_course_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Отзывы", pages_otzuv_path, class: "nav-link" %>
    </li>
        <% if logged_in? %>
        <li class="nav-item">
          <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
          
          </li>
        <li class="nav-item">
        <%= link_to 'Выйти', logout_path, class: "nav-link", method: :delete %>
      </li>
      <% else %>
        <li class="nav-item">
        <%= link_to 'Войти', login_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Регистрация', signup_path, class: "nav-link" %>
      </li>
      <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    
    <%= favicon_link_tag %> 
    <title>MotoBro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
     <%= render  'layouts/navbar' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>







    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.username, micropost.user, class: "btn-dark" %></span>
  <span class="content"><%= micropost.content %></span>
  <% if micropost.picture?  %>
  <%= cl_image_tag("#{micropost.picture}", :width => 300, :height => 200, :crop => :fill, :cloud_name => "elcaronossam") %>
 <% end %>
  <span class="timestamp">
    Опубликовано <%= time_ago_in_words(micropost.created_at) %> назад.
    <% if  current_user.admin? %>
    | <%= link_to "delete", micropost, method: :delete,
                                data: { confirm: "Ты уверен?" } %>
<% end %>
    </span>
</li>

app/views/pages/about.html.erb
<h1 class="text-center">MotoBro</h1>
<p class="text-center">Привет друг! Если ты находишься на этой страничке, значит ты приобрёл курс от MotoBro!</p>
<p class="text-center">Заходи в наш канал и чат!</p>

<div class="container text-center">
    <h2>Канал по програмированию &copy; <%= link_to "RoR", "https://t.me/joinchat/UNFTFxPuFrRiajCD", class: "text-secondary" %></h2>
    <h2>Чат по програмированию &copy; <%= link_to "Frendly chat", "https://t.me/rorofmotobro", class: "text-secondary" %></h2>
    <h2>Mой  &copy; <%= link_to "GitHub", "https://github.com/ElcaroNossam/motobratiki", class: "text-secondary" %></h2>

    
    
    </div>

app/views/pages/course.html.erb
<% if logged_in? %>
<h1 class="text-center"> Материалы курса </h1>
 <div class="row justify-content-md-center">
  <div class="col-4 mt-4">
   <div class="card text-center shadow mb-5 bg-white rounded">
     <div class="card-body">
   
        <%= link_to "Часть 1", "https://youtu.be/L6p151k5nlg", class: "btn btn-outline-info" %>
        <%= link_to "Часть 2", "https://youtu.be/5tMaFKqVgGs", class: "btn btn-outline-primary" %>
        <%= link_to "Часть 3", "https://youtu.be/ibWatKSPzDk", class: "btn btn-outline-success" %>
        <%= link_to "Часть 4", "https://youtu.be/KmhUeZF-oz8", class: "btn btn-outline-danger" %>
    </div>
   </div>
  </div>
 </div>

<div class="container text-center">
    <h2 class="text-dark">Ссылка на мой  GitHub, где тебе надо будет копировать код!</h2>
    <h4>  &copy; <%= link_to "GitHub", "https://github.com/ElcaroNossam/motobratiki", class: "text-danger" %></h4>
</div>

<div class="container text-center">
    <h2 class="text-dark">Если что-то не получается, то пиши в чат, поможем!</h2>
    <h4>  &copy; <%= link_to "Telegram", "https://t.me/rorofmotobro", class: "text-info" %></h4>
</div>

<div class="container text-center">
    <h2 class="text-dark">Продолжаем учить Ruby здесь!</h2>
    <h4>  &copy; <%= link_to "Ruby", "http://rubyschool.us", class: "text-warning" %></h4>
</div>
<div class="container text-center">
    <h2 class="text-dark">После курса Романа учим Ruby on Rails по этой книге!</h2>
    <h4>  &copy; <%= link_to "RoR", "https://www.softcover.io/read/db8803f7/ruby_on_rails_tutorial_3rd_edition_russian/", class: "text-success" %></h4>
</div>
<% else %>

<h1 class="text-center text-danger mt-4"> ААА, не бро! Так не пойдёт, вначале регестрируйся! </h1>
<div class="container text-center">
    <h3 class="text-dark">Для регистрации нужен код. За кодом ко мне в инстаграм!</h3>
    <h4>  &copy; <%= link_to "Instagram", "https://instagram.com/_ok_nel_set_?igshid=1hpw8a1ojq0sv", class: "text-secondary" %></h4>
</div>

<% end %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-black">
    <h1 class="display-4 ">Авторский курс "Вход в мир IT"</h1>
    <% if logged_in? %>
    <h4>В этом курсе мы вместе создадим твой собственный сайт!</h4>
    <% else %>
    <h2>Для получения кода доступа пиши в  &copy; <%= link_to "Instagram", "https://instagram.com/_ok_nel_set_?igshid=1hpw8a1ojq0sv", class: "text-secondary" %></h2>
    <% end %>
    <hr class="my-4">
    <% if logged_in? %>
    <%= link_to "Курс", pages_course_path, class: "btn btn-dark btn-lg" %>
    <% else %>
    <%= link_to "Регистрация нового МотоБрата!", signup_path, class: "btn btn-success btn-lg" %>
   <% end %>
   
  </div>
</div>

app/views/pages/otzuv.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
        <%= render 'shared/stats' %>
      </section>

      
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8 mt-4" id="ot">
    <h3>Отзывы</h3>
    <%= render 'shared/feed' %>
  </div>
  </div>
<% else %>

<div class="row">
  <aside class="col-md-4 mt-5">
    <section class="user_info ">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
    </section>

     


  </aside>
  <div class="col-md-8 ">
  <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
    <aside class="col-md-4 mt-4 ">
      <h3>Отзывы (<%= @user.microposts.count %>)</h3>
 
      </aside>
      <%= render 'shared/stats' %>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <div class="flickr_pagination">
      <%= will_paginate @microposts %>
      </div>
    <% end %>
    
  </div>
</div>
<% end %>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>

    <%= render 'shared/errors', obj: @micropost %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
    <span class="picture">
    <%= f.file_field :picture %>
  </span>
  <% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    Подписки
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Подписчики
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.username %></h1>
<span><%= link_to "Смотреть профиль", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "review") %> </span>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>

    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Подписаться", class: "btn btn-primary" %>
  <% end %>

app/views/users/_follow_form.html.erb
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row" id="groupe">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Выбери себе ник..." %>
          </div>
        </div>

        <div class="form-group row" id="groupe">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Напиши свой емейл..." %>
          </div>
        </div>

        <div class="form-group row" id="groupe">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Придумай пароль..." %>
          </div>
        </div>
        <% if !logged_in? %>

        <div class="form-group row" id="groupe">
        <%= f.label :code, class: "col-2 col-form-label text-light" %>
        <div class="col-10"> 
          <%= f.text_field :code, class: "form-control shadow rounded", placeholder: "Напиши свой код..." %>
        </div>
      </div>
      <% end %>

        <div class="form-group row justify-content-center" id="groupe">
          <%= f.submit(@user.new_record? ? "Регистрация" : "Обновить аккаунт", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
   
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Отписаться", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.username, user %>
    <% if current_user.admin?  %>
        | <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "Ты уверен?" } %>
    <% end %>
  </li>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Обновить свой профиль</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Мото Братья</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
          <h5 class="card-title">
          <%= link_to gravatar_for(user, size: 150), user %>
        </h5>
      <% @user = user %>
  <%= render 'follow_form' if logged_in? %>

            <%= link_to "Смотреть профиль", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Изменить профиль", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Удалить профиль", user_path(user), class: "btn btn-outline-danger", method: :delete,
                data: {confirm: "Уверен сто хочешь удалить?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Регистрация МотоБрата</h1>
<%= render 'form' %>

app/views/users/show.html.erb
 
  <h1 class="text-center mt-4"><%= @user.username %> </h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center mt-4 btn-lg">
<%= render 'shared/stats' %>
<% unless @user == current_user %>
<%= render 'follow_form' if logged_in? %>
<% end %>
</div>


<% if  @user == current_user %>
<div class="text-center mt-4 btn-lg">

  <%= link_to "Добавить фото", "https://ru.gravatar.com/", class: "btn btn-outline-success" %>
    <%= link_to "Изменить профиль", edit_user_path(@user), class: "btn btn-outline-info" %>
    <%= link_to "Удалить профиль", user_path(current_user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Ты уверен?" } %> 
  </div>


<% end %>

<% if logged_in? && @user == current_user %>


<h3 class="text-center  mt-4">Познакомимся?</h3>
<div class="row justify-content-md-center">
<div class="col-4 mt-2">
  <div class="card text-center shadow mb-5 bg-white rounded">
    <div class="card-body">

<%= link_to "Клац", "https://youtu.be/AC01YoK5Sg4", class: "btn btn-dark btn-lg"%>
     </div>
    </div>
   </div>
  </div>

  <h3 class="text-center  mt-4">Если ты готов приступить, тогда в путь!</h3>
  <div class="row justify-content-md-center">
  <div class="col-4 mt-2">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-body">
  
  <%= link_to "Курс", pages_course_path, class: "btn btn-warning btn-lg"%>
       </div>
      </div>
     </div>
    </div>

<% end %>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.username %></h1>
      <span><%= link_to "Смотреть профиль", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>